eureka:
  client:
    serviceUrl:
      defaultZone: http://rstyro:rstyropwd@localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: customer-ribbon-hystrix

server:
  port: 8901

# 第一次请求报超时异常的解决方案：
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000