server:
  port: 8904
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://rstyro:rstyropwd@localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: customer-feign-default
   

logging:
  level:
    top.lrshuai.cloud.springcloud.feign.FeignClientService: DEBUG


    