security:
  basic:
    enabled: true
  user:
    name: rstyro
    password: rstyropwd

server:
  port: 8761

#  在默认设置下，该服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为，
# 设置eureka.client.register-with-eureka=false  表示不向注册中心注册自己
#  与 eureka.client.fetch-registry=false         表示自己就是注册中心，并不需要检索服务
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://rstyro:rstyropwd@localhost:8761/eureka

  datacenter: springcloud
  environment: dev
      
      