server:
  port: 8901
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://rstyro:rstyropwd@localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: customer-feign-hystrix
    
# 不知道feign 默认是不是关闭hystrix,如果不开启，则hystrix 无效
feign.hystrix.enabled: true